version: '3'
services:
  api:
    build:
      context: .
      dockerfile: graph_api/Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - .:/app/
  
  ui:
    build:
      context: .
      dockerfile: relationship-graph-viewer/Dockerfile
    volumes:
    - .:/app/
    ports:
    - "3000:3000"
    # links:
    # - api